spring:
  application:
    name: multi-tenant-test
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres